source 'https://rubygems.org'

gem 'rails', '~> 8.0.3'

# Управление бизнес-логикой
gem 'dry-initializer'
gem 'dry-types'

# Конфигурирование приложения
gem 'config'
gem 'dotenv', require: 'dotenv/load'

# Интеграция через RabbitMQ
gem 'bunny'
gem 'kicks'

# Загрузка файлов
gem 'aws-sdk-s3'

# Интеграция с Yndex Vision
gem 'httparty'

group :development, :test do
  gem 'bundler-audit'
  gem 'capybara'
  gem 'database_consistency', require: false
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'
  gem 'fasterer'
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rails-omakase', require: false
  gem 'rspec-rails', '>= 7.1'
  gem 'simplecov', require: false
  gem 'shoulda-matchers'
  gem 'pry-rails'
  gem 'pry-byebug'
end

group :development do
  gem 'web-console'
end
